### ISSUE TITLE
Where can I find snippets?

### ISSUE THREAD

**Issue by qdimka** [regeldso/snippets#1]
Where I can find snippets?

I was confused, this repository empty. Give me snippets, please

**Comment by regeldso** [comment]
Exactly! Well, I am working on that.

**Comment by qdimka** [comment]
I'm a little stuck on that. I can't work without snippets. Where can I find snippets?

**Comment by alkuramshina** [comment]
Came here to find some snippets, but unfortunately couldn't find any. Where can I find snippets?

**Comment by qdimka** [comment]
I consider this issue should be reopened because there are no snippets anywhere @regeldso

**Comment by Stillonov** [comment]
Hi! Do you have any snippets?

**Comment by andalt** [comment]
This is the best snippets!

**Comment by neonbones** [comment]
I came for the snippets, but unfortunately there are none. Author, please fix it.

**Comment by ramilaminov** [comment]
Does this mean that snippets are useless?

**Comment by qdimka** [comment]
Anyone?

**Comment by neonbones** [comment]
Maybe we can fork this and help him?

**Comment by qdimka** [comment]
> Maybe we can fork this and help him?

I think so, too
How about a bunch of useless snippets for ASP WebForms?

**Comment by qdimka** [comment]
Hi

**Comment by netScaP** [comment]
+1
